### ISSUE TITLE
Already uploaded files are missing for the check

### ISSUE THREAD

**Issue by flaggada** [jegelstaff/formulize#148]
Hello

If you decide to set a file upload box as "required", when you first upload a file you can save your entry but if you want to modify your entry, with a file already uploaded, when you want to save your modifications, it will said that the file is missing (you can see it uploaded, but it check not uploaded).

Thanks :-)

**Comment by eikonos** [comment]
In my testing on the master branch, editing an existing entry which has a required file upload, and not uploading a new file is okay... no error is displayed. Is this the right way to trigger this issue?

**Comment by flaggada** [comment]
Hello eikonos, sorry for the delay, I wanted to check something. 
The problem seems to appears only with old forms, after the update. Because when I create new forms, the problem doesn't appear.
I want to check this with a multipage form, but I can't create a second page, I've already open a new issue here: https://github.com/jegelstaff/formulize/issues/165

Thanks

**Comment by flaggada** [comment]
It seems that problem with the upload element is lying in a multipage form. The problem doesn't exist in a one page form. It's not possible to send a picture, in a multipage form (or maybe it is but you don't see it after the upload). When you go back or when you look in the list of entries, you see that nothing is uploaded... 
With a required file or not.

**Comment by flaggada** [comment]
I think you can close this issue with new version, multipage works now. But an error is lying here: https://github.com/jegelstaff/formulize/issues/210
