### ISSUE TITLE
Error: number of pages being saved does not match number of pages in this screen!

### ISSUE THREAD

**Issue by flaggada** [jegelstaff/formulize#165]
Hello

With the last commit version, updating  my website, when creating a new multipage form, at the moment to create a second page, the following message displays:
Error: number of pages being saved does not match number of pages in this screen!

Thanks

**Comment by jegelstaff** [comment]
Oooh. There was a branch that included some significant changes to the multipage screen admin UI. If you're finding this error, I would strongly suggest you downgrade to a prior version. We should sort this out asap, since we don't want the admin UI broken in the current build.

**Comment by flaggada** [comment]
You're right, thanks, I've replace the file /admin/screen.php before commit https://github.com/jegelstaff/formulize/pull/120 , and that works. 
Now I can see the strange issue with the upload element in a multipage form. The problem doesn't exist in a one page form. It's not possible to send a picture, in a multipage form. When you go back or when you look in the list of entries, you see nothing. But that is another issue, already opened here
https://github.com/jegelstaff/formulize/issues/148
Thanks

**Comment by eikonos** [comment]
I've fixed this issue just now by adjusting the ID used to track the pages, to match the new ID of the tab where the pages are listed.
