### ISSUE TITLE
Overlapping elements on Admin page.

### ISSUE THREAD

**Issue by Torboto** [jegelstaff/formulize#174]
[Screenshot](http://d.pr/i/l7bL)

**Comment by jnip** [comment]
So I looked at this problem. I found where the toolbars and text are created but I don't know how to fix it (I'm an HTML noobie).

The right toolbar is created in formulize\modules\formulize\admin at the end of the file where it uses "$apps[$i]['header']".

The left text, toolbar (Add a Form button and possible text above) and table, are created in formulize\templates_c\default-formulize_standalone^%%17^17B^17B264EA%%home_sections.html.php

The content in these two parts will currently overlap with each other.

**Comment by jujinfu** [comment]
it should be the template files under modules/formulize/admin/templates/admin.

**Comment by jnip** [comment]
ah yes.

It is: modules/formulize/admin/templates/admin/home_sections.html

**Comment by MORich-1** [comment]
This appears to be a CSS issue.

**Comment by jnip** [comment]
#196
