### ISSUE TITLE
Missing template does not prompt user to update modules

### ISSUE THREAD

**Issue by ghost** [jegelstaff/formulize#175]
Currently, when a template cannot be found in the database (because it's newly created, e.g.) no template will be loaded and the user sees an empty page (or empty tab).

Instead, the user should be alerted to the error and prompted to update their modules (e.g. "Formulize couldn't find a template for this page/tab. Do you want to try updating your modules?").

**Comment by Torboto** [comment]
@susannahkirby 
When exactly does this happen (ie What page or part of the site)? Is this for new elements in a form? Does it occur anywhere else?

**Comment by susannahkirby** [comment]
It happened for me in a new Admin tab for setting multiple permissions across several forms in a single application.
But Daniel made it sound like it's a common thing, when you have an entirely new template (i.e. one where there isn't an older version in the DB).  
If you wanted to recreate this... you might be able to pull down the multiple permissions branch and try to click on the "Permissions" icon from within an app's accordian on the Admin view. (That's how I ran into it.) You should get the a view where the Permissions tab is highlighted but there's nothing in the template window below it.
