### ISSUE TITLE
When forms have been deleted, they remain in the left-hand sidebar 'Form Menu' and "General Forms" menu as broken links, or redirect to the home page.

### ISSUE THREAD

**Issue by MORich-1** [jegelstaff/formulize#176]
![screenshot_issue](https://cloud.githubusercontent.com/assets/10062206/6070434/a170f304-ad62-11e4-84d2-68a02fab52b6.png)

**Comment by jujinfu** [comment]
you mean delete a form? or delete a screen?  I was working on something related to this and I think I know how to fix it.

**Comment by jujinfu** [comment]
I can just add a function to check if item exists before loading all these links.
