### ISSUE TITLE
Uploading a file in a multipage form doesn't work

### ISSUE THREAD

**Issue by flaggada** [jegelstaff/formulize#210]
Hello

With last commits, it's not possible to upload a file, in a multipage form. You go on the next page but the file isn't uploaded.
Curiously, in a regular form (single page), no problem, you can do that.

Thanks

**Comment by eikonos** [comment]
Pull request #211 fixes the file upload bug, and it was just merged into the master branch. :)

**Comment by flaggada** [comment]
Cool thanks :-)
