### ISSUE TITLE
Searching in the "User who last modified entry" field in a list fails with a blank page.

### ISSUE THREAD

**Issue by eikonos** [jegelstaff/formulize#214]
This code "$elementObject = $element_handler->get($key);" in entriesdisplay.php tries to load an element for mod_uid, which fails, and then when the 'ele_type' property is accessed, it causes a fatal PHP error.

**Comment by jegelstaff** [comment]
In entriesdisplay.php around line 4567 there is this code: if ("creation_uid" == $key OR "entry_id" == $key) {

That should include a check for mod_uid and for creator_email also.

And it should set $ele_type to 'date' when key is creation_datetime or mod_datetime.

And searches on the creation user/mod user columns, and the creation/mod date columns, and the creator e-mail column, should be checked to see that they work properly. Once upon a time I think the user searches actually required a number? I think both might work now. Test searching by user id number, and by text value of their name.

And then as per the docs on making tests, it would be great to have some Selenium tests for this functionality added to the codebase.

**Comment by jegelstaff** [comment]
Fixed!
