### ISSUE TITLE
Info: latest version

### ISSUE THREAD

**Issue by cesagonchu** [jegelstaff/formulize#217]
Please, where is formulize module latest version for Xoops?
Here:
http://github.com/jegelstaff/formulize/tree/master/modules/formulize
or here:
http://www.freeform.ca/en/formulize-downloads

Will you make this module compatible with XOOPS 2.6.0?
http://github.com/XOOPS/XoopsCore

**Comment by jegelstaff** [comment]
The one at the Freeform website would be the most reliable.

Have they broken backwards compatibility in XOOPS 2.6? It should work okay unless they've changed something.

**Comment by cesagonchu** [comment]
Ok, thanks for your answer :-)
The modules in XOOPS 2.5.x are supposed compatible beings, but as there are big changes in XOOPS 2.6.0, the ideal is to check. I will test if you wish, but for now, I still take care of the bugs with Xoops 2.5.7.1 and soon 2.5.8
