### ISSUE TITLE
Module installation fails - improper SQL

### ISSUE THREAD

**Issue by skenow** [jegelstaff/formulize#296]
Installation fails when trying to update the database - missing a comma in formulize/sql/mysql.sql at line 332, after "send_digests tinyint(1) NOT NULL default 0"

>   note text,
>  send_digests tinyint(1) NOT NULL default 0
>  PRIMARY KEY  (`id_form`)
> ) ENGINE=MyISAM;

This works

>   note text,
>  send_digests tinyint(1) NOT NULL default 0,
>  PRIMARY KEY  (`id_form`)
> ) ENGINE=MyISAM;

Environment: PHP 5.6
MySQL 5.7.25-ubuntu
ImpressCMS 1.3.11
Database driver: PDO

**Comment by jegelstaff** [comment]
Ack! Thanks Steve!
