### ISSUE TITLE
Upgrade instructions? 4.06 to the latest stable release

### ISSUE THREAD

**Issue by skenow** [jegelstaff/formulize#297]
There seems to be no other place to ask questions, so I'll ask here - redirect as needed.

I have a number of sites running Formulize in ImpressCMS, all of which are at version 4.06. In the past, I have seen upgrade scripts to run when going to a new version, and I am not finding them in this branch or your latest zip file.

I want to be sure that the forms, their data, and notifications migrate to the new version.

**Comment by jegelstaff** [comment]
Hi Steve, this is totally the right place.

Formulize is "smart" enough now to detect the state of your database schema/structure and prompt you to run the upgrade script. As you may have found out, after applying the updated files, when you go to any admin page of the module, you get a notice in the upper right with a button to click to apply the DB patches.

Other than that, the only upgrade steps are what you would typically expect: update the module under Modules to read in new templates. That's about it.

How's it going?! :)

**Comment by jegelstaff** [comment]
One other thing, you need MySQL/MariaDB to be running NOT in strict mode.

Also, you don't need to include the docs folder and the ci folder in the install, they are just there for GitHub.
