### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by grichardomi** [jegelstaff/formulize#307]
Can anyone point to stand alone installation instructions?

**Comment by jegelstaff** [comment]
Hello, thanks for the interest :)

formulize.org is the website with reference materials and instructions. Although it is dated a long time ago, the process is still what you find in the readme here: http://www.formulize.org/files/Formulize_Standalone_4.02_Final_Readme.pdf

If you run into any issues, or you want to brainstorm about an application, just drop a line.

Also FYI, there will be a community gathering later this year, probably September, in Toronto.

Take it easy,
--Julian
