### ISSUE TITLE
Form screen broken when date field's minimum is set to another field

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#335]
Getting the following error when loading a form that has date field's minimum set to another date field on the form.

> ﻿﻿Fatal error: Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in /modules/formulize/class/elementrenderer.php on line 964

Based on the error log, the following was passed: `date( $format = 'Y-m-d', $timestamp = '' )`. It's affecting blank new form where the other date field hasn't been initialized yet. Existing entries with the date field initialized loaded properly.

Test on PHP8.1.6 with up to commit [c6bbd52](https://github.com/jegelstaff/formulize/commit/c6bbd52b1186d627575bbeb79748247417d1ce58) applied.

**Comment by jegelstaff** [comment]
Thanks for this. I think if you wrap the getDateElementDefault() function inside intval() then this will resolve itself? We don't want to change the return value of getDateElementDefault because an empty string is relevant elsewhere that this function is used.

**Comment by jegelstaff** [comment]
Actually, I have a better solution... if there is no default returned, then don't set the extra. Watch for another commit soon that will contain that.

**Comment by jegelstaff** [comment]
if($limit_past AND $pastSeedDate = getDateElementDefault($ele_value["date_past_days"], $entry_id)) {
                            $form_ele->setExtra(" min-date='".date('Y-m-d', $pastSeedDate)."' ");
                        }
                        if($limit_future AND $futureSeedDate = getDateElementDefault($ele_value["date_future_days"], $entry_id)) {
                            $form_ele->setExtra(" max-date='".date('Y-m-d', $futureSeedDate)."' ");
                        }

**Comment by tikyon** [comment]
Thanks, Julian. This works.
