### ISSUE TITLE
Cannot log in when site is turned off

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#352]
If we turn off the website that uses Anari theme, the following message is displayed after submitting valid login credential: 

> This page cannot be displayed due to an internal error.
> You can provide the following information to the administrators of this site to help them solve the problem:
> 
> Error: Handler does not exist
> Module: profile
> Name: profile

The only way to get back in (if logged off) is to turn on the site via modifying the config value in the database.

**Comment by jegelstaff** [comment]
This is fixed with commit 39ed4bd4b2b261047fb6e9c2676f0000f84445cd
