### ISSUE TITLE
Error when deleting an entry after commit b64cb69b

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#367]
Getting the following message when deleting from list screen

> Error deleting entry X from the database for form Y

I traced it to the usage of `array_filter($ids, 'is_int')` in `deleteEntries()` (modules/formulize/class/data.php) which would return an empty array because `$ids` contains numeric string items rather than integer. One possible fix is to use `is_numeric` instead.

**Comment by jegelstaff** [comment]
Yes, absolutely!

**Comment by jegelstaff** [comment]
Fixed in commit f77863f617a88ea77ce44da9b7c7ed8474c0bedc
