### ISSUE TITLE
Printable view showing JavaScript code when using subform

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#389]
When using subform of collapsible or flat form types, the script is displayed on the page before rendering the subform rows. It doesn't happen when displaying the subform in table rows.

The script shown is from file modules/formulize/include/formdisplay.php  [around Line 2567](https://github.com/jegelstaff/formulize/blob/16353fa8cc674daaa5936b9a259111f5cc05bf87/modules/formulize/include/formdisplay.php#L2567) and [Line 2590](https://github.com/jegelstaff/formulize/blob/16353fa8cc674daaa5936b9a259111f5cc05bf87/modules/formulize/include/formdisplay.php#L2590).

I suspect that the opening `<script>` was not included properly.

**Comment by jegelstaff** [comment]
Ack! I guess 7.21 is closer to reality that I thought.

I have made a PR that I think fixes this. Please check it out: https://github.com/jegelstaff/formulize/pull/390
