### ISSUE TITLE
Fatal error: Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#392]
When deleting an entry from list screen, the entry is correct deleted but then the page reloads with error below

> Fatal  error: Uncaught TypeError: call_user_func(): Argument 1 ($callback) must be a valid callback, function "form_51_on_delete" not found or invalid function name in modules/formulize/class/forms.php on line 417
> 
> Stack trace:
> 0 modules/formulize/class/data.php(253): formulizeForm->onDelete('53')
> 1 modules/formulize/include/functions.php(928): formulizeDataHandler->deleteEntries(Array)
> 2 modules/formulize/include/functions.php(990): deleteIdReq('53', 51)
> 3 modules/formulize/include/entriesdisplay.php(132): deleteEntry('53', '', 51)
> 4 modules/formulize/class/listOfEntriesScreen.php(342): displayEntries(51, '', '', 0, 0, Object(formulizeListOfEntriesScreen))
> 5 modules/formulize/initialize.php(273): formulizeListOfEntriesScreenHandler->render(Object(formulizeListOfEntriesScreen), '', '')
> 6 modules/formulize/index.php(71): include('modules/formulize/initialize.php')
> 7 {main}
>   thrown in modules/formulize/class/forms.php on line 417

**Comment by jegelstaff** [comment]
Yes! :( We've seen the same thing. I will sort it out tonight. Thanks for the report. Sorry for the trouble!

**Comment by jegelstaff** [comment]
I believe this is resolved in e6fd8ba097eb1019626b34a36cd1918bd04640a1 

Let me know if that does the trick for you.

The commit seems to have touched every line due to either CR issues or white space issues. Anyway, to view the diff without whitespace changes, append ?w=1 to the end of the GitHub URL.
