### ISSUE TITLE
Password box - Uncaught TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#491]
This happens on modules/profile/edituser.php when user that cannot edit their username types into the password box. The displayed message will remain as "Too short" for whatever the user has typed in.

From Chrome console
> Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
>     at $.fn.teststrength (password_strength_plugin.js:86:45)
>     at HTMLInputElement.<anonymous> (password_strength_plugin.js:62:25)
>     at HTMLInputElement.dispatch (jquery.min.js:3:12444)
>     at r.handle (jquery.min.js:3:9173)

Firefox console
> Uncaught TypeError: uname is undefined

Webmasters group didn't run into this issue because it has the username textbox available on the form.

**Comment by jegelstaff** [comment]
Thank you. Will check it out.

**Comment by jegelstaff** [comment]
Fixed in e07d11c62d6c3bb57c367d39f34e9c98ad325ead
