### ISSUE TITLE
Validating PHP code doesn't work right now

### ISSUE THREAD

**Issue by jegelstaff** [jegelstaff/formulize#499]
Check the comment in formulize_validatePHPCode function. Need a reliable way to check for syntax errors in code the user writes, so we don't break the entire application by saving invalid code!!!

**Comment by arvinsingla** [comment]
Might be overkill but one thought could be to push the code through a linter. I’ve been playing with command line php linters to help us with the code base so it could live in the project. We might be able to stream the string to the linter and receive the output. Totally hypothetical.

**Comment by jegelstaff** [comment]
The current setup should be able to work through formulize.net at least, I think? There's a command line thing that will check syntax. Can't solve runtime errors of course, but the syntax checking is an important low bar. I think this will work or can be made to work on f.net but is server dependent on other systems, so the core code may retain this being off. Or really... make it a preference. Off by default. Duh.
