### ISSUE TITLE
"Undefined array key [hashed string]" warning

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#555]
https://github.com/jegelstaff/formulize/blob/4b57f2321a409d0ae4564187655442eea5bbea20/modules/formulize/include/formdisplaypages.php#L481

I notice that there's a lot "Undefined array key [hashed string]" in the log, should it just be = assignment rather than a string concatenation?

**Comment by jegelstaff** [comment]
Yup! Thank you. Fixed in https://github.com/jegelstaff/formulize/commit/73cbaa5008512f308ce2d429a5bf02a9863ff3a0
