### ISSUE TITLE
Recurring PHP warnings

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#556]
Here are a few more high recurring warnings from my log:

https://github.com/jegelstaff/formulize/blob/d5e66daa3b3d1305e98548a44a9217eae056252e/modules/formulize/class/fileUploadElement.php#L107
- "Trying to access array offset on value of type bool" for lines 107-109.

https://github.com/jegelstaff/formulize/blob/d5e66daa3b3d1305e98548a44a9217eae056252e/modules/formulize/include/extract.php#L938
- "Trying to access array offset on value of type bool" for lines 938-939

https://github.com/jegelstaff/formulize/blob/d5e66daa3b3d1305e98548a44a9217eae056252e/modules/formulize/include/extract.php#L979
- Trying to access array offset on value of type int
- Uninitialized string offset 1

https://github.com/jegelstaff/formulize/blob/d5e66daa3b3d1305e98548a44a9217eae056252e/modules/formulize/include/extract.php#L1823
- Undefined array key "snapshot"

https://github.com/jegelstaff/formulize/blob/d5e66daa3b3d1305e98548a44a9217eae056252e/modules/formulize/include/formdisplay.php#L3953
- Trying to access array offset on value of type null

**Comment by jegelstaff** [comment]
Hello, thanks for these @tikyon I believe the linked PR addresses the lines you pointed out. Much appreciated. One subtle bug in there (what you reported on line 979, the structure of the array was not being setup correctly in some cirucmstances). Please test on some instance where you've seen these errors and check if they go away. Thanks!

**Comment by tikyon** [comment]
Thanks for the fixes. I tested them and they look good.

I can confirm that line 979 error is gone now. In my instance, it happens when `$filter` is string value.
